import { apiFetch, type ShareLink } from '@/lib/api';
import styles from './share-links.module.css';

export const revalidate = 0;

async function fetchShareLinks() {
  try {
    // The backend doesn't have a list endpoint for share links — we call sync/pull to get summary data
    const sync = await apiFetch<{ syncVersion: number; documents: Array<{ id: string; title: string }> }>(
      '/v1/sync/pull',
      { method: 'POST', body: JSON.stringify({ sinceVersion: 0 }) },
    );
    return { sync, error: '' };
  } catch (e) {
    return { sync: null, error: String(e) };
  }
}

export default async function ShareLinksPage() {
  const { sync, error } = await fetchShareLinks();

  return (
    <div>
      <h1 className={styles.pageTitle}>Share Links</h1>
      <p className={styles.pageSubtitle}>
        Share links are generated by the mobile app via <code>/v1/share-links</code>.
        They expire after the time set by the user.
      </p>

      {error && <div className={styles.error}>{error}</div>}

      <div className={styles.infoCard}>
        <div className={styles.infoIcon}>🔗</div>
        <div>
          <div className={styles.infoTitle}>Share links are document-scoped</div>
          <div className={styles.infoBody}>
            When a user creates a share link in the app, it&apos;s stored in the backend&apos;s JSON store
            (or Postgres when connected). To list all active links, add a <code>GET /v1/share-links</code> endpoint
            to the backend&apos;s <code>app.ts</code> that reads from <code>store.shareLinks</code>.
          </div>
        </div>
      </div>

      {sync && (
        <div className={styles.docList}>
          <h2 className={styles.sectionTitle}>Synced documents ({sync.documents.length})</h2>
          <p className={styles.sectionHint}>These are the documents that could potentially have share links.</p>
          {sync.documents.length === 0 && <p className={styles.empty}>No documents synced yet.</p>}
          {sync.documents.map((doc: { id: string; title: string }) => (
            <div key={doc.id} className={styles.docRow}>
              <span className={styles.docTitle}>{doc.title}</span>
              <span className={styles.docId}>{doc.id}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
